"""Initial schema

Revision ID: 546ed63ee6a8
Revises: None
Create Date: 2026-05-20 18:00:48.418724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546ed63ee6a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('unit_system', sa.Enum('METRIC', 'IMPERIAL', name='unitsystem'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('body_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('left_arm_cm', sa.Float(), nullable=True),
    sa.Column('right_arm_cm', sa.Float(), nullable=True),
    sa.Column('left_thigh_cm', sa.Float(), nullable=True),
    sa.Column('right_thigh_cm', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_body_measurements_user_logged', 'body_measurements', ['user_id', 'logged_at'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.Enum('CARDIO', 'STRENGTH', name='exercisetype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exercise_logs_user_date', 'exercise_logs', ['user_id', 'log_date'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('fiber_per_100g', sa.Float(), nullable=False),
    sa.Column('sugar_per_100g', sa.Float(), nullable=False),
    sa.Column('sodium_per_100g', sa.Float(), nullable=False),
    sa.Column('saturated_fat_per_100g', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.Enum('API', 'BARCODE', 'CUSTOM', 'AI_SCAN', name='foodsource'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index('idx_food_items_barcode', 'food_items', ['barcode'], unique=False)
    op.create_index('idx_food_items_created_by', 'food_items', ['created_by'], unique=False)
    op.create_index('idx_food_items_name', 'food_items', ['name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('LOSE', 'MAINTAIN', 'GAIN', name='goaltype'), nullable=False),
    sa.Column('current_weight_kg', sa.Float(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activitylevel'), nullable=False),
    sa.Column('weekly_pace_kg', sa.Float(), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=False),
    sa.Column('daily_protein_g', sa.Integer(), nullable=False),
    sa.Column('daily_carbs_g', sa.Integer(), nullable=False),
    sa.Column('daily_fat_g', sa.Integer(), nullable=False),
    sa.Column('daily_fiber_g', sa.Integer(), nullable=False),
    sa.Column('daily_water_ml', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('water_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_water_logs_user_date', 'water_logs', ['user_id', 'log_date'], unique=False)
    op.create_table('weight_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weight_entries_user_logged', 'weight_entries', ['user_id', 'logged_at'], unique=False)
    op.create_table('exercise_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_log_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_log_id'], ['exercise_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_item_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACKS', name='mealtype'), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_log_entries_user_date', 'food_log_entries', ['user_id', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_food_log_entries_user_date', table_name='food_log_entries')
    op.drop_table('food_log_entries')
    op.drop_table('exercise_sets')
    op.drop_index('idx_weight_entries_user_logged', table_name='weight_entries')
    op.drop_table('weight_entries')
    op.drop_index('idx_water_logs_user_date', table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_food_items_name', table_name='food_items')
    op.drop_index('idx_food_items_created_by', table_name='food_items')
    op.drop_index('idx_food_items_barcode', table_name='food_items')
    op.drop_table('food_items')
    op.drop_index('idx_exercise_logs_user_date', table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index('idx_body_measurements_user_logged', table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
