from typing import List, Dict, Any
from app.models.exercise import ExerciseType

EXERCISE_LIBRARY: List[Dict[str, Any]] = [
    # Cardio Exercises (with MET values for calorie calculation)
    # Calorie formula: MET * 3.5 * weight_kg / 200 * duration_minutes
    {"name": "Running (8 km/h - 12 min/mile)", "type": ExerciseType.CARDIO, "met": 8.3, "muscle_group": None},
    {"name": "Running (9.6 km/h - 10 min/mile)", "type": ExerciseType.CARDIO, "met": 9.8, "muscle_group": None},
    {"name": "Running (11.3 km/h - 8.5 min/mile)", "type": ExerciseType.CARDIO, "met": 11.0, "muscle_group": None},
    {"name": "Running (12.8 km/h - 7.5 min/mile)", "type": ExerciseType.CARDIO, "met": 11.8, "muscle_group": None},
    {"name": "Walking (4.8 km/h - moderate pace)", "type": ExerciseType.CARDIO, "met": 3.5, "muscle_group": None},
    {"name": "Walking (6.4 km/h - brisk pace)", "type": ExerciseType.CARDIO, "met": 5.0, "muscle_group": None},
    {"name": "Cycling (16-19 km/h - light effort)", "type": ExerciseType.CARDIO, "met": 6.0, "muscle_group": None},
    {"name": "Cycling (20-25 km/h - moderate effort)", "type": ExerciseType.CARDIO, "met": 8.0, "muscle_group": None},
    {"name": "Swimming (freestyle - light/moderate effort)", "type": ExerciseType.CARDIO, "met": 5.8, "muscle_group": None},
    {"name": "Swimming (freestyle - vigorous effort)", "type": ExerciseType.CARDIO, "met": 9.8, "muscle_group": None},
    {"name": "Elliptical Trainer (moderate effort)", "type": ExerciseType.CARDIO, "met": 5.0, "muscle_group": None},
    {"name": "Rowing Machine (moderate effort)", "type": ExerciseType.CARDIO, "met": 7.0, "muscle_group": None},
    {"name": "Rope Jumping (moderate pace)", "type": ExerciseType.CARDIO, "met": 11.0, "muscle_group": None},
    {"name": "Hiking (cross-country)", "type": ExerciseType.CARDIO, "met": 6.0, "muscle_group": None},
    {"name": "HIIT (High-Intensity Interval Training)", "type": ExerciseType.CARDIO, "met": 8.0, "muscle_group": None},
    {"name": "Yoga", "type": ExerciseType.CARDIO, "met": 2.5, "muscle_group": None},
    {"name": "Zumba / Aerobic Dancing", "type": ExerciseType.CARDIO, "met": 6.5, "muscle_group": None},
    {"name": "Stairmaster / Stair climbing", "type": ExerciseType.CARDIO, "met": 9.0, "muscle_group": None},
    {"name": "Calisthenics (vigorous effort)", "type": ExerciseType.CARDIO, "met": 8.0, "muscle_group": None},
    {"name": "Pilates", "type": ExerciseType.CARDIO, "met": 3.0, "muscle_group": None},
    
    # Strength Exercises (with target muscle groups)
    {"name": "Bench Press (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Chest"},
    {"name": "Chest Fly (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Chest"},
    {"name": "Incline Bench Press (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Chest"},
    {"name": "Decline Bench Press (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Chest"},
    {"name": "Push-up", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Chest"},
    {"name": "Cable Crossover", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Chest"},
    {"name": "Squat (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Quads"},
    {"name": "Leg Press (Machine)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Quads"},
    {"name": "Leg Extension (Machine)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Quads"},
    {"name": "Lunge (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Quads"},
    {"name": "Bulgarian Split Squat", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Quads"},
    {"name": "Deadlift (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Hamstrings / Lower Back"},
    {"name": "Romanian Deadlift (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Hamstrings / Glutes"},
    {"name": "Leg Curl (Machine)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Hamstrings"},
    {"name": "Hip Thrust (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Glutes"},
    {"name": "Pull-up", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Back"},
    {"name": "Lat Pulldown (Cable)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Back"},
    {"name": "Bent Over Row (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Back"},
    {"name": "One-Arm Row (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Back"},
    {"name": "Seated Cable Row", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Back"},
    {"name": "Overhead Shoulder Press (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Shoulders"},
    {"name": "Military Press (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Shoulders"},
    {"name": "Lateral Raise (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Shoulders"},
    {"name": "Front Raise (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Shoulders"},
    {"name": "Rear Delt Fly (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Shoulders"},
    {"name": "Biceps Curl (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Biceps"},
    {"name": "Hammer Curl (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Biceps"},
    {"name": "Preacher Curl (Ez-Bar)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Biceps"},
    {"name": "Triceps Pushdown (Cable)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Triceps"},
    {"name": "Overhead Triceps Extension (Dumbbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Triceps"},
    {"name": "Triceps Dip", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Triceps"},
    {"name": "Crunch", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Abs"},
    {"name": "Plank", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Abs"},
    {"name": "Hanging Leg Raise", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Abs"},
    {"name": "Russian Twist", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Abs"},
    {"name": "Calf Raise (Machine)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Calves"},
    {"name": "Shrug (Barbell)", "type": ExerciseType.STRENGTH, "met": None, "muscle_group": "Traps"}
]
